package com.study.basic;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.springframework.util.StringUtils;

public class MapLineTest {
    public static void main(String[] args){
        String partVtree = "label_id\tname\tcode\n"
                + "v_1K\tStreet Fun\tentertainment#humor#street_fun\n"
                + "v_1Y\tThriller\tentertainment#film#thriller\n"
                + "v_20\tDocument\tentertainment#film#document\n"
                + "v_2o\tAstrology\tentertainment#astrology&divination#astrology\n"
                + "v_2p\tTarot\tentertainment#astrology&divination#tarot\n"
                + "v_2t\tBollywood Dance\tentertainment#dance#bollywood_dance\n"
                + "v_2x\tEntertainment Industry\tentertainment#entertainment_industry\n"
                + "v_2A\tEvents & Listings\tentertainment#events&listings\n"
                + "v_2J\tCute\tentertainment#comics&animation#cute\n"
                + "v_2K\tFantasy\tentertainment#comics&animation#fantasy\n"
                + "v_2L\tFunny\tentertainment#comics&animation#funny\n"
                + "v_2M\tHorror\tentertainment#comics&animation#horror\n"
                + "v_2O\tScience Fiction\tentertainment#comics&animation#science_fiction\n"
                + "v_2P\tVintage\tentertainment#comics&animation#vintage\n"
                + "v_2R\tCartoon\tentertainment#cartoon\n"
                + "v_2Z\tTik Tok\tentertainment#status#tik_tok\n"
                + "v_30\tPoems\tentertainment#status#poems\n"
                + "v_31\tDubsmash\tentertainment#status#dubsmash\n"
                + "v_3c\tDesign\tart#visual_art&design#design\n"
                + "v_3e\tSculpture\tart#visual_art&design#sculpture\n"
                + "v_3f\tArt Museums & Galleries\tart#visual_art&design#art_museums&galleries\n"
                + "v_3g\tBody Art\tart#visual_art&design#body_art\n"
                + "v_3w\tFonts & Calligraphy\tart#visual_art&design#fonts&calligraphy\n"
                + "v_41\tBicycles\tautos&vehicles#bicycles\n"
                + "v_46\tBMX Bikes\tautos&vehicles#bicycles#bmx_bikes\n"
                + "v_47\tCruiser Bicycles\tautos&vehicles#bicycles#cruiser_bicycles\n"
                + "v_48\tKids' Bikes\tautos&vehicles#bicycles#kids__bikes\n"
                + "v_49\tMountain Bikes\tautos&vehicles#bicycles#mountain_bikes\n"
                + "v_4b\tBoats & Watercraft\tautos&vehicles#boats&watercraft\n"
                + "v_4c\tCampers & RVs\tautos&vehicles#motor_vehicles#campers&rvs\n"
                + "v_4f\tBus\tautos&vehicles#commercial_vehicles#bus\n"
                + "v_4n\tPersonal Aircraft\tautos&vehicles#aircraft#personal_aircraft\n"
                + "v_4s\tVehicle Parts & Services\tautos&vehicles#vehicle_parts&services\n"
                + "v_4t\tVehicle Parts & Accessories\tautos&vehicles#vehicle_parts&services#vehicle_parts&accessories\n"
                + "v_4u\tVehicle Repair & Maintenance\tautos&vehicles#vehicle_parts&services#vehicle_repair"
                + "&maintenance\n"
                + "v_4z\tBeauty Pageants\tbeauty&fitness#beauty_pageants\n"
                + "v_4H\tPerfumes & Fragrances\tbeauty&fitness#face&body_care#perfumes&fragrances\n"
                + "v_4I\tHygiene & Toiletries\tbeauty&fitness#face&body_care#hygiene&toiletries\n"
                + "v_52\tHair\tbeauty&fitness#hair\n"
                + "v_53\tHair Accessories\tbeauty&fitness#hair#hair_accessories\n"
                + "v_54\tHair Care\tbeauty&fitness#hair#hair_care\n"
                + "v_57\tHairstyles\tbeauty&fitness#hair#hairstyles\n"
                + "v_58\tMen's Beauty\tbeauty&fitness#mens_beauty\n"
                + "v_59\tBeard\tbeauty&fitness#mens_beauty#beard\n"
                + "v_5a\tNail\tbeauty&fitness#nail\n"
                + "v_5b\tNail Art\tbeauty&fitness#nail#nail_art\n"
                + "v_5d\tBusiness & Industry\tbusiness&industry\n"
                + "v_5e\tAdvertising & Marketing\tbusiness&industry#advertising&marketing\n"
                + "v_5g\tPublic Relations\tbusiness&industry#advertising&marketing#public_relations\n"
                + "v_5l\tAerospace & Defense\tbusiness&industry#aerospace&defense\n"
                + "v_5m\tSpace Technology\tbusiness&industry#aerospace&defense#space_technology\n"
                + "v_5o\tAgriculture & Forestry\tbusiness&industry#agriculture&forestry\n"
                + "v_5q\tAquaculture\tbusiness&industry#agriculture&forestry#aquaculture\n"
                + "v_5v\tLivestock\tbusiness&industry#agriculture&forestry#livestock\n"
                + "v_5x\tAutomotive Industry\tbusiness&industry#automotive_industry\n"
                + "v_5y\tBusiness Finance\tbusiness&industry#business_finance\n"
                + "v_5A\tVenture Capital\tbusiness&industry#business_finance#venture_capital\n"
                + "v_5D\tBusiness Operations\tbusiness&industry#business_operations\n"
                + "v_5E\tHuman Resources\tbusiness&industry#business_operations#human_resources\n"
                + "v_5F\tBusiness Plans & Presentations\tbusiness&industry#business_operations#business_plans"
                + "&presentations\n"
                + "v_5G\tManagement\tbusiness&industry#business_operations#management\n"
                + "v_5H\tBusiness Services\tbusiness&industry#business_services\n"
                + "v_5I\tOffice Services\tbusiness&industry#business_services#office_services\n"
                + "v_5K\tE-Commerce Services\tbusiness&industry#business_services#e_commerce_services\n"
                + "v_5L\tCorporate Events\tbusiness&industry#business_services#corporate_events\n"
                + "v_5P\tWriting & Editing Services\tbusiness&industry#business_services#writing&editing_services\n"
                + "v_5T\tConsulting\tbusiness&industry#business_services#consulting\n"
                + "v_5U\tChemicals Industry\tbusiness&industry#chemicals_industry\n"
                + "v_5W\tCleaning Agents\tbusiness&industry#chemicals_industry#cleaning_agents\n"
                + "v_60\tConstruction & Maintenance\tbusiness&industry#construction&maintenance\n"
                + "v_61\tBuilding Materials & Supplies\tbusiness&industry#construction&maintenance#building_materials"
                + "&supplies\n"
                + "v_65\tEnergy & Utilities\tbusiness&industry#energy&utilities\n"
                + "v_67\tElectricity\tbusiness&industry#energy&utilities#electricity\n"
                + "v_6c\tHospitality Industry\tbusiness&industry#hospitality_industry\n"
                + "v_6d\tEvent Planning\tbusiness&industry#hospitality_industry#event_planning\n"
                + "v_6e\tFood Service\tbusiness&industry#hospitality_industry#food_service\n"
                + "v_6f\tIndustrial Materials & Equipment\tbusiness&industry#industrial_materials&equipment\n"
                + "v_6h\tHeavy Machinery\tbusiness&industry#industrial_materials&equipment#heavy_machinery\n"
                + "v_6j\tManufacturing\tbusiness&industry#manufacturing\n"
                + "v_6l\tMetals & Mining\tbusiness&industry#metals&mining\n"
                + "v_6m\tPrecious Metals\tbusiness&industry#metals&mining#precious_metals\n"
                + "v_6n\tPharmaceuticals & Biotech\tbusiness&industry#pharmaceuticals&biotech\n"
                + "v_6o\tPrinting & Publishing\tbusiness&industry#printing&publishing\n"
                + "v_6q\tRetail Trade\tbusiness&industry#retail_trade\n"
                + "v_6r\tRetail Equipment & Technology\tbusiness&industry#retail_trade#retail_equipment&technology\n"
                + "v_6s\tTransportation & Logistics\tbusiness&industry#transportation&logistics\n"
                + "v_6v\tMoving & Relocation\tbusiness&industry#transportation&logistics#moving&relocation\n"
                + "v_6y\tMail & Package Delivery\tbusiness&industry#transportation&logistics#mail&package_delivery\n"
                + "v_6A\tMaritime Transport\tbusiness&industry#transportation&logistics#maritime_transport\n"
                + "v_6B\tRail Transport\tbusiness&industry#transportation&logistics#rail_transport\n"
                + "v_6C\tUrban Transport\tbusiness&industry#transportation&logistics#urban_transport\n"
                + "v_6D\tParking\tbusiness&industry#transportation&logistics#parking\n"
                + "v_6G\tComputer & Electronics\tcomputer&electronics\n"
                + "v_6H\tCAD & CAM\tcomputer&electronics#cad&cam\n"
                + "v_6I\tComputer Hardware\tcomputer&electronics#computer_hardware\n"
                + "v_6J\tComputer Components\tcomputer&electronics#computer_hardware#computer_components\n"
                + "v_6K\tDesktop Computers\tcomputer&electronics#computer_hardware#desktop_computers\n"
                + "v_6L\tLaptops & Notebooks\tcomputer&electronics#computer_hardware#laptops&notebooks\n"
                + "v_6M\tComputer Peripherals\tcomputer&electronics#computer_hardware#computer_peripherals\n"
                + "v_6N\tComputer Drives & Storage\tcomputer&electronics#computer_hardware#computer_drives&storage\n"
                + "v_6Q\tComputer Security\tcomputer&electronics#computer_security\n"
                + "v_6T\tConsumer Electronics\tcomputer&electronics#consumer_electronics\n"
                + "v_6U\tAudio Equipment\tcomputer&electronics#consumer_electronics#audio_equipment\n"
                + "v_6W\tTV & Video Equipment\tcomputer&electronics#consumer_electronics#tv&video_equipment\n"
                + "v_6X\tCar Electronics\tcomputer&electronics#consumer_electronics#car_electronics\n"
                + "v_6Y\tCamera & Photo Equipment\tcomputer&electronics#consumer_electronics#camera&photo_equipment\n"
                + "v_70\tGame Systems & Consoles\tcomputer&electronics#consumer_electronics#game_systems&consoles\n"
                + "v_72\tDrones & RC Aircraft\tcomputer&electronics#consumer_electronics#drones&rc_aircraft\n"
                + "v_75\tVirtual Reality Devices\tcomputer&electronics#consumer_electronics#virtual_reality_devices\n"
                + "v_76\tElectronics & Electrical\tcomputer&electronics#electronics&electrical\n"
                + "v_77\tElectronic Components\tcomputer&electronics#electronics&electrical#electronic_components\n"
                + "v_7a\tPower Supplies\tcomputer&electronics#electronics&electrical#power_supplies\n"
                + "v_7d\tEnterprise Technology\tcomputer&electronics#enterprise_technology\n"
                + "v_7e\tCustomer Relationship Management (CRM)"
                + "\tcomputer&electronics#enterprise_technology#customer_relationship_management_crm\n"
                + "v_7g\tData Management\tcomputer&electronics#enterprise_technology#data_management\n"
                + "v_7h\tNetworking\tcomputer&electronics#networking\n"
                + "v_7l\tVPN & Remote Access\tcomputer&electronics#networking#vpn&remote_access\n"
                + "v_7n\tProgramming\tcomputer&electronics#programming\n"
                + "v_7o\tDevelopment Tools\tcomputer&electronics#programming#development_tools\n"
                + "v_7q\tJava (Programming Language)\tcomputer&electronics#programming#java_programming_language\n"
                + "v_7r\tScripting Languages\tcomputer&electronics#programming#scripting_languages\n"
                + "v_7s\tWindows & .NET\tcomputer&electronics#programming#windows&net\n"
                + "v_7t\tSoftware\tcomputer&electronics#software\n"
                + "v_7w\tOperating Systems\tcomputer&electronics#software#operating_systems\n"
                + "v_7x\tInternet Software\tcomputer&electronics#software#internet_software\n"
                + "v_7z\tMultimedia Software\tcomputer&electronics#software#multimedia_software\n"
                + "v_7A\tBusiness & Productivity Software\tcomputer&electronics#software#business"
                + "&productivity_software\n"
                + "v_7D\tFinance\tfinance\n"
                + "v_7E\tAccounting & Auditing\tfinance#accounting&auditing\n"
                + "v_7F\tTax Preparation & Planning\tfinance#accounting&auditing#tax_preparation&planning\n"
                + "v_7G\tBilling & Invoicing\tfinance#accounting&auditing#billing&invoicing\n"
                + "v_7I\tBanking\tfinance#banking\n"
                + "v_7J\tATMs & Branch Locations\tfinance#banking#atms&branch_locations\n"
                + "v_7K\tDebit & Checking Services\tfinance#banking#debit&checking_services\n"
                + "v_7L\tSavings Accounts\tfinance#banking#savings_accounts\n"
                + "v_7M\tMoney Transfer & Wire Services\tfinance#banking#money_transfer&wire_services\n"
                + "v_7N\tCredit & Lending\tfinance#credit&lending\n"
                + "v_7O\tLoans\tfinance#credit&lending#loans\n"
                + "v_7P\tCredit Cards\tfinance#credit&lending#credit_cards\n"
                + "v_7R\tCredit Reporting & Monitoring\tfinance#credit&lending#credit_reporting&monitoring\n"
                + "v_7T\tFinancial Planning & Management\tfinance#financial_planning&management\n"
                + "v_7U\tRetirement & Pension\tfinance#financial_planning&management#retirement&pension\n"
                + "v_7X\tGrants, Scholarships & Financial Aid\tfinance#grants_scholarships&financial_aid\n"
                + "v_80\tStudy Grants & Scholarships\tfinance#grants_scholarships&financial_aid#study_grants"
                + "&scholarships\n"
                + "v_81\tInsurance\tfinance#insurance\n"
                + "v_82\tHealth Insurance\tfinance#insurance#health_insurance\n"
                + "v_87\tInvesting\tfinance#investing\n"
                + "v_88\tCurrencies & Foreign Exchange\tfinance#investing#currencies&foreign_exchange\n"
                + "v_89\tCommodities & Futures Trading\tfinance#investing#commodities&futures_trading\n"
                + "v_8f\tStocks & Bonds\tfinance#investing#stocks&bonds\n"
                + "v_8g\tFood & Drink\tfood&drink\n"
                + "v_8h\tDrinks\tfood&drink#drinks\n"
                + "v_8i\tAlcoholic Drinks\tfood&drink#drinks#alcoholic_drinks\n"
                + "v_8j\tNon Alcoholic Drinks\tfood&drink#drinks#non_alcoholic_drinks\n"
                + "v_8k\tWater\tfood&drink#drinks#water\n"
                + "v_8l\tFood\tfood&drink#food\n"
                + "v_8m\tCooking & Recipes\tfood&drink#cooking&recipes\n"
                + "v_8o\tCooking Tips\tfood&drink#cooking&recipes#cooking_tips\n"
                + "v_8p\tBaked Goods\tfood&drink#food#baked_goods\n"
                + "v_8q\tStreet Food\tfood&drink#food#street_food\n"
                + "v_8s\tGrocery Retailers\tfood&drink#grocery_retailers\n"
                + "v_8y\tRestaurants\tfood&drink#restaurants\n"
                + "v_8z\tRestaurant Reviews & Reservations\tfood&drink#restaurants#restaurant_reviews&reservations\n"
                + "v_8A\tFast Food\tfood&drink#restaurants#fast_food\n"
                + "v_8C\tPizzerias\tfood&drink#restaurants#pizzerias\n"
                + "v_8E\tMeal Planning\tfood&drink#meal_planning\n"
                + "v_8G\tArcade & Coin-Op Games\tgames#arcade&coin_op_games\n"
                + "v_8H\tBoard Games\tgames#board_games\n"
                + "v_8I\tChess & Abstract Strategy Games\tgames#board_games#chess&abstract_strategy_games\n"
                + "v_8J\tMiniatures & Wargaming\tgames#board_games#miniatures&wargaming\n"
                + "v_8K\tCard Games\tgames#card_games\n"
                + "v_8Y\tHentai Game/X-rated Game\tgames#electronic_games#hentai_game/x_rated_game\n"
                + "v_90\tLove Game\tgames#electronic_games#love_game\n"
                + "v_91\tMud Game\tgames#electronic_games#mud_game\n"
                + "v_93\tEducation Game\tgames#electronic_games#education_game\n"
                + "v_96\tFamily-Oriented Games & Activities\tgames#party_games#family_oriented_games&activities\n"
                + "v_99\tParty Games\tgames#party_games\n"
                + "v_9a\tPuzzles & Brainteasers\tgames#puzzles&brainteasers\n"
                + "v_9c\tTable Games\tgames#table_games\n"
                + "v_9B\tHealth\thealth\n"
                + "v_9H\tHealth Conditions\thealth#health_conditions\n"
                + "v_9I\tSkin Conditions\thealth#health_conditions#skin_conditions\n"
                + "v_9J\tCancer\thealth#health_conditions#cancer\n"
                + "v_9K\tHeart & Hypertension\thealth#health_conditions#heart&hypertension\n"
                + "v_9L\tEating Disorders\thealth#health_conditions#eating_disorders\n"
                + "v_9N\tAllergies\thealth#health_conditions#allergies\n"
                + "v_9Q\tBlood Sugar & Diabetes\thealth#health_conditions#blood_sugar&diabetes\n"
                + "v_9R\tInfectious Diseases\thealth#health_conditions#infectious_diseases\n"
                + "v_9U\tNeurological Conditions\thealth#health_conditions#neurological_conditions\n"
                + "v_9V\tInjury\thealth#health_conditions#injury\n"
                + "v_9W\tObesity\thealth#health_conditions#obesity\n"
                + "v_9X\tPain Management\thealth#health_conditions#pain_management\n"
                + "v_9Z\tGenetic Disorders\thealth#health_conditions#genetic_disorders\n"
                + "v_a0\tEar Nose & Throat\thealth#health_conditions#ear_nose&throat\n"
                + "v_ae\tMental Health\thealth#mental_health\n"
                + "v_ag\tAnxiety & Stress\thealth#mental_health#anxiety&stress\n"
                + "v_ah\tDepression\thealth#mental_health#depression\n"
                + "v_ai\tNursing\thealth#nursing\n"
                + "v_ak\tNutrition\thealth#nutrition\n"
                + "v_al\tVitamins & Supplements\thealth#nutrition#vitamins&supplements\n"
                + "v_am\tOral & Dental Care\thealth#health_conditions#oral&dental_care\n"
                + "v_an\tPediatrics\thealth#health_conditions#pediatrics\n"
                + "v_ao\tDrugs & Medications\thealth#drugs&medications\n"
                + "v_ap\tPublic Health\thealth#public_health\n"
                + "v_aq\tOccupational Health & Safety\thealth#public_health#occupational_health&safety\n"
                + "v_ar\tToxic Substances & Poisoning\thealth#public_health#toxic_substances&poisoning\n"
                + "v_at\tReproductive Health\thealth#health_conditions#reproductive_health\n"
                + "v_aG\tVision Care\thealth#health_conditions#vision_care\n"
                + "v_aM\tClubs\tlifestyle#clubs\n"
                + "v_aN\tBook Discussion Club\thobbies&leisure#clubs#book_discussion_club\n"
                + "v_aO\tBook Sales Club\thobbies&leisure#clubs#book_sales_club\n"
                + "v_aP\tHealth Club\thobbies&leisure#clubs#health_club\n"
                + "v_aQ\tWomen's Club\thobbies&leisure#clubs#womens_club\n"
                + "v_aT\tArt & Craft Supplies\tlifestyle#diy&crafts#art&craft_supplies\n"
                + "v_b3\tWater Activities\tlifestyle#water_activities\n"
                + "v_b4\tBoating\thobbies&leisure#water_activities#boating\n"
                + "v_b5\tSurf & Swim\thobbies&leisure#water_activities#surf&swim\n"
                + "v_b6\tDiving & Underwater Activities\thobbies&leisure#water_activities#diving"
                + "&underwater_activities\n"
                + "v_b7\tPrimitive Living\tlifestyle#primitive_living\n"
                + "v_b8\tHome & Garden\thome&garden\n"
                + "v_b9\tInterior Design\thome&garden#interior_design\n"
                + "v_ba\tLiving Room\thome&garden#interior_design#living_room\n"
                + "v_bb\tBedroom & Bathroom\thome&garden#interior_design#bedroom&bathroom\n"
                + "v_bc\tKitchen & Dining\thome&garden#interior_design#kitchen&dining\n"
                + "v_bd\tLaundry\thome&garden#interior_design#laundry\n"
                + "v_be\tNursery & Playroom\thome&garden#interior_design#nursery&playroom\n"
                + "v_bf\tDressing Room\thome&garden#interior_design#dressing_room\n"
                + "v_bg\tHome Office\thome&garden#interior_design#home_office\n"
                + "v_bh\tHome Storage & Shelving\thome&garden#interior_design#home_storage&shelving\n"
                + "v_bj\tExterior Design\thome&garden#exterior_design\n"
                + "v_bk\tHome Swimming Pools, Saunas & Spas\thome&garden#exterior_design#home_swimming_pools_saunas"
                + "&spas\n"
                + "v_bl\tPatio, Lawn & Garden\thome&garden#exterior_design#patio_lawn&garden\n"
                + "v_bm\tHome Furnishings, Appliances & "
                + "Improvement\thome&garden#home_furnishings_appliances&improvement\n"
                + "v_bn\tHome Furnishings\thome&garden#home_furnishings_appliances&improvement#home_furnishings\n"
                + "v_bo\tHome Appliances\thome&garden#home_furnishings_appliances&improvement#home_appliances\n"
                + "v_bp\tHome Services\thome&garden#home_services\n"
                + "v_bq\tPest Control\thome&garden#home_services#pest_control\n"
                + "v_br\tHome Safety & Security\thome&garden#home_safety&security\n"
                + "v_bs\tInternet & Telecom\tinternet&telecom\n"
                + "v_bt\tCommunications Equipment\tinternet&telecom#communications_equipment\n"
                + "v_bv\tMobile & Wireless\tinternet&telecom#mobile&wireless\n"
                + "v_bw\tMobile & Wireless Accessories\tinternet&telecom#mobile&wireless#mobile&wireless_accessories\n"
                + "v_bx\tMobile Apps & Add-Ons\tinternet&telecom#mobile&wireless#mobile_apps&add_ons\n"
                + "v_by\tMobile Phones\tinternet&telecom#mobile&wireless#mobile_phones\n"
                + "v_bC\tWeb Apps & Online Tools\tinternet&telecom#web_apps&online_tools\n"
                + "v_bK\tWeb Services\tinternet&telecom#web_services\n"
                + "v_bN\tAcademic Conferences & Publications\tjobs&education#education#academic_conferences"
                + "&publications\n"
                + "v_bO\tAlumni & Reunions\tjobs&education#education#alumni&reunions\n"
                + "v_bP\tColleges & Universities\tjobs&education#education#colleges&universities\n"
                + "v_bQ\tComputer Education\tjobs&education#education#computer_education\n"
                + "v_bR\tDistance Learning\tjobs&education#education#distance_learning\n"
                + "v_bS\tEarly Childhood Education\tjobs&education#education#early_childhood_education\n"
                + "v_bT\tHomeschooling\tjobs&education#education#homeschooling\n"
                + "v_bV\tPrivate Tutoring Services\tjobs&education#education#private_tutoring_services\n"
                + "v_bW\tSpecial Education\tjobs&education#education#special_education\n"
                + "v_bY\tStudy Abroad\tjobs&education#education#study_abroad\n"
                + "v_bZ\tTeaching & Classroom Resources\tjobs&education#education#teaching&classroom_resources\n"
                + "v_c0\tTraining & Certification\tjobs&education#education#training&certification\n"
                + "v_c1\tVocational & Continuing Education\tjobs&education#education#vocational&continuing_education\n"
                + "v_c2\tInternships\tjobs&education#internships\n"
                + "v_c7\tBooks & Literature\tjobs&education#books&literature\n"
                + "v_c9\tChildren's Literature\tjobs&education#books&literature#childrens_literature\n"
                + "v_ca\tE-Books\tjobs&education#books&literature#e_books\n"
                + "v_cb\tFan Fiction\tjobs&education#books&literature#fan_fiction\n"
                + "v_cc\tLiterary Classics\tjobs&education#books&literature#literary_classics\n"
                + "v_cd\tMagazines\tjobs&education#books&literature#magazines\n"
                + "v_ce\tPoetry\tjobs&education#books&literature#poetry\n"
                + "v_cf\tWriters Resources\tjobs&education#books&literature#writers_resources\n"
                + "v_ch\tGovernment\tpolitics#government\n"
                + "v_ci\tCourts & Judiciary\tlaw&government#government#courts&judiciary\n"
                + "v_cl\tGovernment Agencies\tlaw&government#government#government_agencies\n"
                + "v_cm\tGovernment Contracting & Procurement\tlaw&government#government#government_contracting"
                + "&procurement\n"
                + "v_cn\tIntelligence\tlaw&government#government#intelligence\n"
                + "v_co\tCounterterrorism\tlaw&government#government#counterterrorism\n"
                + "v_cp\tLegislative Branch\tlaw&government#government#legislative_branch\n"
                + "v_cq\tLobbying\tlaw&government#government#lobbying\n"
                + "v_cr\tPublic Policy\tlaw&government#government#public_policy\n"
                + "v_cs\tState & Local Government\tlaw&government#government#state&local_government\n"
                + "v_ct\tVisa & Immigration\tlaw&government#government#visa&immigration\n"
                + "v_cu\tLegal\tpolitics#legal\n"
                + "v_cv\tAccident & Personal Injury Law\tlaw&government#legal#accident&personal_injury_law\n"
                + "v_cw\tBankruptcy\tlaw&government#legal#bankruptcy\n"
                + "v_cx\tBusiness & Corporate Law\tlaw&government#legal#business&corporate_law\n"
                + "v_cy\tConstitutional Law & Civil Rights\tlaw&government#legal#constitutional_law&civil_rights\n"
                + "v_cz\tCriminal Law\tlaw&government#legal#criminal_law\n"
                + "v_cA\tFamily Law\tlaw&government#legal#family_law\n"
                + "v_cB\tIntellectual Property\tlaw&government#legal#intellectual_property\n"
                + "v_cC\tLabor & Employment Law\tlaw&government#legal#labor&employment_law\n"
                + "v_cD\tLegal Education\tlaw&government#legal#legal_education\n"
                + "v_cE\tLegal Services\tlaw&government#legal#legal_services\n"
                + "v_cN\tPublic Safety\tpolitics#public_safety\n"
                + "v_cO\tCrime & Justice\tlaw&government#public_safety#crime&justice\n"
                + "v_cP\tEmergency Services\tlaw&government#public_safety#emergency_services\n"
                + "v_cQ\tLaw Enforcement\tlaw&government#public_safety#law_enforcement\n"
                + "v_cR\tSecurity Products & Services\tlaw&government#public_safety#security_products&services\n"
                + "v_cU\tDisabled & Special Needs\tsociety#social_issues&advocacy#disabled&special_needs\n"
                + "v_cV\tEthnic & Identity Groups\tculture&tradition#ethnic&identity_groups\n"
                + "v_db\tInspirational & Motivational\tculture&tradition#inspirational&motivational\n"
                + "v_de\tSeniors & Retirement\tsociety#social_issues&advocacy#seniors&retirement\n"
                + "v_dg\tWork & Labor Issues\tsociety#social_issues&advocacy#work&labor_issues\n"
                + "v_dh\tHousing & Development\tsociety#social_issues&advocacy#housing&development\n"
                + "v_di\tDiscrimination & Identity Relations\tsociety#social_issues&advocacy#discrimination"
                + "&identity_relations\n"
                + "v_dj\tCharity & Philanthropy\tsociety#social_issues&advocacy#charity&philanthropy\n"
                + "v_dk\tHuman Rights & Liberties\tsociety#social_issues&advocacy#human_rights&liberties\n"
                + "v_dl\tImmigration Policy & Border Issues\tsociety#social_issues&advocacy#immigration_policy"
                + "&border_issues\n"
                + "v_dn\tWomen's Security\tsociety#social_issues&advocacy#womens_security\n"
                + "v_du\tAnimal Products & Services\tbiology#animal_products&services\n"
                + "v_dv\tAnimal Welfare\tpets&animals#animal_products&services#animal_welfare\n"
                + "v_dw\tPet Food & Pet Care Supplies\tpets&animals#animal_products&services#pet_food"
                + "&pet_care_supplies\n"
                + "v_dx\tVeterinarians\tpets&animals#animal_products&services#veterinarians\n"
                + "v_dG\tReal聽Estate\treal_estate\n"
                + "v_dH\tProperty Development\treal_estate#property_development\n"
                + "v_dI\tReal Estate Listings\treal_estate#real_estate_listings\n"
                + "v_dJ\tReal Estate Services\treal_estate#real_estate_services\n"
                + "v_dK\tScience\tscience\n"
                + "v_dL\tAstronomy\tscience#astronomy\n"
                + "v_dM\tBiological Sciences\tscience#biological_sciences\n"
                + "v_dN\tChemistry\tscience#chemistry\n"
                + "v_dP\tEarth Sciences\tscience#earth_sciences\n"
                + "v_dQ\tEcology & Environment\tscience#ecology&environment\n"
                + "v_dR\tClimate Change & Global Warming\tscience#ecology&environment#climate_change&global_warming\n"
                + "v_dT\tEngineering & Technology\tscience#engineering&technology\n"
                + "v_dU\tMathematics\tscience#mathematics\n"
                + "v_dV\tPhysics\tscience#physics\n"
                + "v_dW\tScientific Equipment\tscience#scientific_equipment\n"
                + "v_dX\tScientific Institutions\tscience#scientific_institutions\n"
                + "v_eg\tSports Competitions\tsports#sports_competitions\n"
                + "v_eh\tOlympics\tsports#sports_competitions#olympics\n"
                + "v_eJ\tSports Coaching & Training\tsports#sports_coaching&training\n"
                + "v_eK\tTravel\ttravel\n"
                + "v_eL\tTransportation\ttravel#transportation\n"
                + "v_eM\tAir Travel\ttravel#transportation#air_travel\n"
                + "v_eN\tBus & Rail\ttravel#transportation#bus&rail\n"
                + "v_eO\tCar Rental & Taxi Services\ttravel#transportation#car_rental&taxi_services\n"
                + "v_eP\tCarpooling & Vehicle Sharing\ttravel#transportation#carpooling&vehicle_sharing\n"
                + "v_eR\tHotels & Accommodations\ttravel#hotels&accommodations\n"
                + "v_eS\tTourist Destinations\ttravel#tourist_destinations\n"
                + "v_eT\tSpeciality Travel\ttravel#speciality_travel\n"
                + "v_eV\tTravel Guides & Vlogs\ttravel#travel_guides&vlogs\n"
                + "v_n2\tAircraft\tautos&vehicles#aircraft\n"
                + "v_n5\tTextiles & Nonwovens\tbusiness&industry#textiles&nonwovens\n"
                + "v_n6\tBreakfast Foods\tfood&drink#food#breakfast_foods\n"
                + "v_n7\tCandy & Sweets\tfood&drink#food#candy&sweets\n"
                + "v_n9\tMeat & Seafood\tfood&drink#food#meat&seafood\n"
                + "v_na\tBBQ & Grilling\tfood&drink#cooking&recipes#bbq&grilling\n"
                + "v_nb\tDesserts\tfood&drink#cooking&recipes#desserts\n"
                + "v_nd\tGamble Games\tgames#gamble_games\n"
                + "v_ne\tParenting\thealth#parenting\n"
                + "v_nf\tToys\tlifestyle#toys\n"
                + "v_nh\tElection\tlaw&government#government#election\n"
                + "v_ni\tParties\tpolitics#parties\n"
                + "v_nj\tChildren\tculture&tradition#family&relationships#children\n"
                + "v_ov\tNursery Rhymes\tentertainment#music&audio#nursery_rhymes\n";

        String partPgc = "垂类\t数量\n"
                + "v_1K\t5\n"
                + "v_1Y\t14\n"
                + "v_20\t12\n"
                + "v_2A\t51\n"
                + "v_2J\t14\n"
                + "v_2K\t3\n"
                + "v_2L\t12\n"
                + "v_2M\t3\n"
                + "v_2O\t1\n"
                + "v_2P\t1\n"
                + "v_2R\t262\n"
                + "v_2Z\t271\n"
                + "v_2o\t224\n"
                + "v_2p\t15\n"
                + "v_2t\t39\n"
                + "v_2x\t562\n"
                + "v_30\t32\n"
                + "v_31\t113\n"
                + "v_3c\t144\n"
                + "v_3e\t19\n"
                + "v_3f\t2\n"
                + "v_3g\t30\n"
                + "v_3w\t17\n"
                + "v_41\t20\n"
                + "v_46\t2\n"
                + "v_47\t1\n"
                + "v_48\t2\n"
                + "v_49\t1\n"
                + "v_4H\t2\n"
                + "v_4I\t2\n"
                + "v_4b\t12\n"
                + "v_4c\t11\n"
                + "v_4f\t8\n"
                + "v_4n\t18\n"
                + "v_4s\t31\n"
                + "v_4t\t17\n"
                + "v_4u\t19\n"
                + "v_4z\t34\n"
                + "v_52\t44\n"
                + "v_53\t1\n"
                + "v_54\t22\n"
                + "v_57\t39\n"
                + "v_58\t19\n"
                + "v_59\t4\n"
                + "v_5A\t1\n"
                + "v_5D\t20\n"
                + "v_5E\t1\n"
                + "v_5F\t54\n"
                + "v_5G\t3\n"
                + "v_5H\t23\n"
                + "v_5I\t1\n"
                + "v_5K\t3\n"
                + "v_5L\t2\n"
                + "v_5P\t1\n"
                + "v_5T\t1\n"
                + "v_5U\t4\n"
                + "v_5W\t1\n"
                + "v_5a\t5\n"
                + "v_5b\t6\n"
                + "v_5d\t320\n"
                + "v_5e\t130\n"
                + "v_5g\t3\n"
                + "v_5l\t15\n"
                + "v_5m\t2\n"
                + "v_5o\t147\n"
                + "v_5q\t10\n"
                + "v_5v\t37\n"
                + "v_5x\t12\n"
                + "v_5y\t24\n"
                + "v_60\t43\n"
                + "v_61\t8\n"
                + "v_65\t9\n"
                + "v_67\t2\n"
                + "v_6A\t2\n"
                + "v_6B\t4\n"
                + "v_6C\t3\n"
                + "v_6D\t3\n"
                + "v_6G\t394\n"
                + "v_6H\t23\n"
                + "v_6I\t22\n"
                + "v_6J\t5\n"
                + "v_6K\t1\n"
                + "v_6L\t3\n"
                + "v_6M\t2\n"
                + "v_6N\t3\n"
                + "v_6Q\t16\n"
                + "v_6T\t86\n"
                + "v_6U\t17\n"
                + "v_6W\t10\n"
                + "v_6X\t2\n"
                + "v_6Y\t8\n"
                + "v_6c\t4\n"
                + "v_6d\t1\n"
                + "v_6e\t1\n"
                + "v_6f\t11\n"
                + "v_6h\t10\n"
                + "v_6j\t27\n"
                + "v_6l\t5\n"
                + "v_6m\t3\n"
                + "v_6n\t7\n"
                + "v_6o\t6\n"
                + "v_6q\t12\n"
                + "v_6r\t2\n"
                + "v_6s\t8\n"
                + "v_6v\t1\n"
                + "v_6y\t2\n"
                + "v_70\t2\n"
                + "v_72\t2\n"
                + "v_75\t2\n"
                + "v_76\t101\n"
                + "v_77\t27\n"
                + "v_7A\t3\n"
                + "v_7D\t98\n"
                + "v_7E\t14\n"
                + "v_7F\t13\n"
                + "v_7G\t2\n"
                + "v_7I\t22\n"
                + "v_7J\t3\n"
                + "v_7K\t3\n"
                + "v_7L\t3\n"
                + "v_7M\t2\n"
                + "v_7N\t8\n"
                + "v_7O\t4\n"
                + "v_7P\t1\n"
                + "v_7R\t1\n"
                + "v_7T\t25\n"
                + "v_7U\t1\n"
                + "v_7X\t4\n"
                + "v_7a\t5\n"
                + "v_7d\t7\n"
                + "v_7e\t1\n"
                + "v_7g\t3\n"
                + "v_7h\t15\n"
                + "v_7l\t2\n"
                + "v_7n\t23\n"
                + "v_7o\t3\n"
                + "v_7q\t3\n"
                + "v_7r\t3\n"
                + "v_7s\t2\n"
                + "v_7t\t51\n"
                + "v_7w\t2\n"
                + "v_7x\t5\n"
                + "v_7z\t51\n"
                + "v_80\t1\n"
                + "v_81\t13\n"
                + "v_82\t2\n"
                + "v_87\t45\n"
                + "v_88\t6\n"
                + "v_89\t11\n"
                + "v_8A\t5\n"
                + "v_8C\t2\n"
                + "v_8E\t19\n"
                + "v_8G\t13\n"
                + "v_8H\t7\n"
                + "v_8I\t7\n"
                + "v_8J\t3\n"
                + "v_8K\t77\n"
                + "v_8Y\t3\n"
                + "v_8f\t36\n"
                + "v_8g\t782\n"
                + "v_8h\t9\n"
                + "v_8i\t1\n"
                + "v_8j\t6\n"
                + "v_8k\t1\n"
                + "v_8l\t347\n"
                + "v_8m\t729\n"
                + "v_8o\t122\n"
                + "v_8p\t13\n"
                + "v_8q\t30\n"
                + "v_8s\t10\n"
                + "v_8y\t11\n"
                + "v_8z\t6\n"
                + "v_90\t3\n"
                + "v_91\t2\n"
                + "v_93\t2\n"
                + "v_96\t15\n"
                + "v_99\t27\n"
                + "v_9B\t524\n"
                + "v_9H\t64\n"
                + "v_9I\t5\n"
                + "v_9J\t1\n"
                + "v_9K\t2\n"
                + "v_9L\t1\n"
                + "v_9N\t1\n"
                + "v_9Q\t4\n"
                + "v_9R\t1\n"
                + "v_9U\t3\n"
                + "v_9V\t2\n"
                + "v_9W\t1\n"
                + "v_9X\t2\n"
                + "v_9Z\t1\n"
                + "v_9a\t36\n"
                + "v_9c\t6\n"
                + "v_a0\t1\n"
                + "v_aG\t8\n"
                + "v_aM\t16\n"
                + "v_aN\t1\n"
                + "v_aO\t2\n"
                + "v_aP\t1\n"
                + "v_aQ\t1\n"
                + "v_aT\t90\n"
                + "v_ae\t11\n"
                + "v_ag\t2\n"
                + "v_ah\t3\n"
                + "v_ai\t10\n"
                + "v_ak\t9\n"
                + "v_al\t6\n"
                + "v_am\t10\n"
                + "v_an\t13\n"
                + "v_ao\t266\n"
                + "v_ap\t70\n"
                + "v_aq\t2\n"
                + "v_ar\t5\n"
                + "v_at\t17\n"
                + "v_b3\t6\n"
                + "v_b4\t2\n"
                + "v_b5\t2\n"
                + "v_b6\t1\n"
                + "v_b7\t15\n"
                + "v_b8\t129\n"
                + "v_b9\t13\n"
                + "v_bC\t532\n"
                + "v_bK\t12\n"
                + "v_bN\t6\n"
                + "v_bO\t4\n"
                + "v_bP\t41\n"
                + "v_bQ\t171\n"
                + "v_bR\t239\n"
                + "v_bS\t113\n"
                + "v_bT\t5\n"
                + "v_bV\t36\n"
                + "v_bW\t320\n"
                + "v_bY\t4\n"
                + "v_bZ\t63\n"
                + "v_ba\t6\n"
                + "v_bb\t3\n"
                + "v_bc\t3\n"
                + "v_bd\t2\n"
                + "v_be\t9\n"
                + "v_bf\t2\n"
                + "v_bg\t1\n"
                + "v_bh\t2\n"
                + "v_bj\t13\n"
                + "v_bk\t1\n"
                + "v_bl\t24\n"
                + "v_bm\t11\n"
                + "v_bn\t9\n"
                + "v_bo\t8\n"
                + "v_bp\t8\n"
                + "v_bq\t2\n"
                + "v_br\t6\n"
                + "v_bs\t660\n"
                + "v_bt\t18\n"
                + "v_bv\t313\n"
                + "v_bw\t63\n"
                + "v_bx\t334\n"
                + "v_by\t203\n"
                + "v_c0\t8\n"
                + "v_c1\t9\n"
                + "v_c2\t3\n"
                + "v_c7\t21\n"
                + "v_c9\t4\n"
                + "v_cA\t2\n"
                + "v_cB\t1\n"
                + "v_cC\t2\n"
                + "v_cD\t13\n"
                + "v_cE\t1\n"
                + "v_cN\t10\n"
                + "v_cO\t16\n"
                + "v_cP\t5\n"
                + "v_cQ\t5\n"
                + "v_cR\t4\n"
                + "v_cU\t5\n"
                + "v_cV\t67\n"
                + "v_ca\t2\n"
                + "v_cb\t2\n"
                + "v_cc\t3\n"
                + "v_cd\t3\n"
                + "v_ce\t29\n"
                + "v_cf\t6\n"
                + "v_ch\t928\n"
                + "v_ci\t3\n"
                + "v_cl\t22\n"
                + "v_cm\t6\n"
                + "v_cn\t15\n"
                + "v_co\t9\n"
                + "v_cp\t6\n"
                + "v_cq\t1\n"
                + "v_cr\t23\n"
                + "v_cs\t750\n"
                + "v_ct\t4\n"
                + "v_cu\t21\n"
                + "v_cv\t2\n"
                + "v_cw\t1\n"
                + "v_cx\t3\n"
                + "v_cy\t6\n"
                + "v_cz\t2\n"
                + "v_dG\t58\n"
                + "v_dH\t7\n"
                + "v_dI\t4\n"
                + "v_dJ\t8\n"
                + "v_dK\t252\n"
                + "v_dL\t24\n"
                + "v_dM\t12\n"
                + "v_dN\t8\n"
                + "v_dP\t12\n"
                + "v_dQ\t17\n"
                + "v_dR\t9\n"
                + "v_dT\t68\n"
                + "v_dU\t22\n"
                + "v_dV\t12\n"
                + "v_dW\t11\n"
                + "v_dX\t7\n"
                + "v_db\t329\n"
                + "v_de\t3\n"
                + "v_dg\t9\n"
                + "v_dh\t31\n"
                + "v_di\t67\n"
                + "v_dj\t27\n"
                + "v_dk\t18\n"
                + "v_dl\t3\n"
                + "v_dn\t1\n"
                + "v_du\t18\n"
                + "v_dv\t14\n"
                + "v_dw\t15\n"
                + "v_dx\t3\n"
                + "v_eJ\t26\n"
                + "v_eK\t329\n"
                + "v_eL\t21\n"
                + "v_eM\t10\n"
                + "v_eN\t113\n"
                + "v_eO\t4\n"
                + "v_eP\t2\n"
                + "v_eR\t9\n"
                + "v_eS\t168\n"
                + "v_eT\t18\n"
                + "v_eV\t352\n"
                + "v_eg\t46\n"
                + "v_eh\t1\n"
                + "v_n2\t1\n"
                + "v_n5\t4\n"
                + "v_n6\t2\n"
                + "v_n7\t1\n"
                + "v_n9\t2\n"
                + "v_na\t1\n"
                + "v_nb\t3\n"
                + "v_nd\t50\n"
                + "v_ne\t11\n"
                + "v_nf\t74\n"
                + "v_nh\t3\n"
                + "v_ni\t7\n"
                + "v_nj\t1\n"
                + "v_ov\t1\n";

        Map<String,String> nameMap =
                Arrays.stream(partVtree.split("\n")).map(s -> s.split("\t")).collect(Collectors.toMap(s->s[0],
                        s->s[1]+"\t"+s[2]));
        Map<String,String> pgcMap =
                Arrays.stream(partPgc.split("\n")).map(s -> s.split("\t")).collect(Collectors.toMap(s->s[0],s->s[1]));

        String str = StringUtils.collectionToDelimitedString(pgcMap.keySet(),",","\"","\"");
        System.out.println(str);

        for(Map.Entry<String,String> entry : nameMap.entrySet()){
            System.out.println(entry.getKey()+"\t"+entry.getValue()+"\t"+pgcMap.get(entry.getKey()));
        }



    }
}
